# Zone Fade Detector - Configuration Example
# Copy this file to config.yaml and customize as needed

# Symbol Configuration
symbols:
  - SPY  # S&P 500 ETF (proxy for /ES)
  - QQQ  # NASDAQ 100 ETF (proxy for /NQ)
  - IWM  # Russell 2000 ETF (proxy for /RTY)

# Data Polling Configuration
polling:
  interval_seconds: 30  # How often to poll for new data
  max_retries: 3        # Maximum retry attempts for failed requests
  timeout_seconds: 10   # Request timeout in seconds
  batch_size: 100       # Number of bars to fetch per request

# Technical Indicators Configuration
indicators:
  vwap:
    enabled: true
    standard_deviations: [1, 2]  # VWAP bands to calculate
    lookback_hours: 6.5          # Hours of data for VWAP calculation
  
  opening_range:
    enabled: true
    duration_minutes: 30         # Opening range duration
  
  swing_structure:
    enabled: true
    lookback_bars: 20            # Bars to look back for swing detection
    min_swing_size: 0.1          # Minimum price move for swing (percentage)
  
  volume_analysis:
    enabled: true
    expansion_threshold: 1.5     # Volume expansion multiplier
    contraction_threshold: 0.7   # Volume contraction multiplier

# Zone Detection Configuration
zones:
  prior_day:
    enabled: true
    high_weight: 1.0
    low_weight: 1.0
  
  weekly:
    enabled: true
    high_weight: 1.2
    low_weight: 1.2
  
  value_area:
    enabled: true
    percentile_threshold: 70     # Volume percentile for value area
    fallback_to_prior_high_low: true

# Quality Rating System (QRS) Configuration
qrs:
  zone_quality:
    htf_relevance_weight: 2.0
    zone_strength_weight: 1.0
  
  rejection_clarity:
    pin_bar_weight: 2.0
    engulfing_weight: 1.5
    long_wick_weight: 1.0
  
  structure_flip:
    choch_weight: 2.0
    structure_break_weight: 1.0
  
  context:
    vwap_slope_weight: 1.0
    value_area_overlap_weight: 1.0
    trend_day_penalty: -1.0
  
  intermarket_divergence:
    etf_divergence_weight: 2.0
    sector_rotation_weight: 1.0
  
  # Minimum score for A-Setup classification
  a_setup_threshold: 7

# Alert Configuration
alerts:
  channels:
    - console
    - file
    # - email
    # - webhook
  
  min_qrs_score: 7              # Minimum QRS score to generate alert
  deduplication_minutes: 5      # Minutes to wait before duplicate alerts
  max_alerts_per_hour: 10       # Rate limiting for alerts
  
  console:
    enabled: true
    show_details: true
    color_output: true
  
  file:
    enabled: true
    log_file: logs/alerts.log
    max_file_size: 10485760     # 10MB
    backup_count: 5
  
  email:
    enabled: false
    smtp_server: smtp.gmail.com
    smtp_port: 587
    username: ${ALERT_EMAIL_USERNAME}
    password: ${ALERT_EMAIL_PASSWORD}
    from_address: ${ALERT_EMAIL_FROM}
    to_addresses:
      - ${ALERT_EMAIL_TO}
  
  webhook:
    enabled: false
    url: ${WEBHOOK_URL}
    secret: ${WEBHOOK_SECRET}
    timeout: 5

# Logging Configuration
logging:
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: logs/zone_fade_detector.log
  max_file_size: 10485760       # 10MB
  backup_count: 5
  console_output: true

# Performance Configuration
performance:
  max_concurrent_requests: 5
  request_timeout: 10
  retry_attempts: 3
  retry_delay: 1.0              # Initial delay in seconds
  retry_backoff: 2.0            # Exponential backoff multiplier
  
  # Memory management
  max_cached_bars: 10000        # Maximum bars to keep in memory
  cache_cleanup_interval: 300   # Seconds between cache cleanups
  
  # Data processing
  batch_processing: true
  batch_size: 1000
  processing_timeout: 30

# Market Hours Configuration
market_hours:
  timezone: US/Eastern
  regular_hours:
    start: "09:30"
    end: "16:00"
  premarket_hours:
    start: "04:00"
    end: "09:30"
  after_hours:
    start: "16:00"
    end: "20:00"
  
  # Days of the week (0=Monday, 6=Sunday)
  trading_days: [0, 1, 2, 3, 4]  # Monday to Friday

# Risk Management Configuration
risk_management:
  max_daily_alerts: 50          # Maximum alerts per day
  cooldown_minutes: 15          # Minutes between alerts for same symbol
  position_size_limit: 1000     # Maximum position size (if implementing execution)
  stop_loss_percentage: 0.02    # 2% stop loss
  take_profit_percentage: 0.04  # 4% take profit

# Development Configuration
development:
  debug_mode: false
  mock_data: false
  test_mode: false
  verbose_logging: false
  
  # Test data configuration
  test_data:
    start_date: "2024-01-01"
    end_date: "2024-01-31"
    symbols: ["SPY", "QQQ", "IWM"]